### PR TITLE
Framework for supporting multiple years of data

### PR DESCRIPTION
**Pull request by ghing**
This pull request does not implement all the vintages of every geotype that users are likely to need, but it does set up the API necessary to add this:

- Adds a `--year` argument to the CLI, defaulting to the most recent year
- Adds a `year` argument to the downloader class constructors which sets `self.year`
- Removes the year from the `PROCESSED_NAME` attribute
- Replaces the `YEAR` attribute in the downloader classes with `YEAR_LIST`
- Implements multiple years of data for counties and the cartographic versions of counties as a reference implementation
- Implements multiple years of data for tracts (the classes were already there) as a reference implementation for cases where both fields and URLs vary between vintages
- Maps out the general pattern for adding support for additional vintages more widely in the README

This will be a breaking change for any consumer code that imports the year-based classes. I could continue to support them fairly easily, but it seems not great to expose them through the public API.

I wanted to send this pull request sooner rather than later so the maintainers can review the approach and also so it can get into the master branch ASAP to make it easier for others to contribute support for additional years.

If this is merged, I'll continue to add support for additional years. Issue #8  might be a good place for people to request particular vintages to prioritize.

Finally, this seems like it should get a minor version bump, but I wasn't sure how you all handle versioning, so I left `setup.py` untouched.

### CODE REVIEW

**Comment by palewire** [comment]
Great. Would it possible to add one or two tests that pull different years?

**Comment by ghing** [comment]
Yes, I will add a couple of tests soon.

**Comment by ghing** [comment]
I added tests in ea8dbcc.

**Comment by ghing** [comment]
@palewire, just bumping this. Let me know if you want to see any additional tests.

**Comment by palewire** [comment]
Should the BaseDownloader YEAR_LIST keep `[2018]` as the default, or does that need to be upgraded as well?

**Pull request merged**
